version: 2.1

jobs:
  run-hello-world:

    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Say Hello
          command: echo "Hello World!"
          
workflows:
  version: 2
  test-workflow:
    jobs:
      - run-hello-world
